// models/FormData.js
const mongoose = require('mongoose');

const formDataSchema = new mongoose.Schema({
  activityInfoForm: {
    mainActivity: String,
    mainActivityStart: String,
    secondaryActivity: String,
    secondaryActivityStart: String,
    activityAddress: String,
    adressNumber: String,
    postalCodeActivity: String,
    wilaya: String,
    municipality: String,
    activityCode: String,
    employeNumber: String,
    phone: String,
    fax: String,
    email: String,
    legalForm: String,
    nationality: String,
    totalAnnualIncome: String,
    taxRegime: String,
    registrationDate: String,
    personalAddress: String,
    personalWilaya: String,
    personalMunicipality: String,
    hasBranches: String,
    branchCount: String,
    taxBenefit1: String,
    taxCode1: String,
    taxBenefit2: String,
    taxCode2: String,
    financialYearEndDate: String,
  },
  declarationInfo: {
    declarationPlace: String,
    declarationDate: String,
  },
  generalInfoForm: {
    fullName: String,
    address: String,
    nationalId: String,
    nationalIdNumber: String,
    city: String,
    state: String,
    country: String,
    postalCode: String,
    symbole: String,
    phoneNumber: String,
    faxNumber: String,
    legalFormType: String,
    nationality: String,
    birthDate: String,
    genderMale: Boolean,
    genderFemale: Boolean,
    accountingPeriod: String,
    socialSecurityHead: String,
    bankingSystemType: String,
    registrationDate: String,
    registrationMonth: String,
    registrationYear: String,
    registrationCode: String,
    referenceDate: String,
    referenceMonth: String,
    referenceYear: String,
    applicationDate: String,
    applicationMonth: String,
    applicationYear: String,
    legalEntityBasic: String,
    legalEntityAdvanced: String,
    legalEntitysimple: String,
    legalEntityCommercial: String,
    legalEntityNonCommercial: String,
    documentDate: String,
    documentMonth: String,
    documentYear: String,
    changeDate: String,
    modificationDate: String,
    modificationMonth: String,
    modificationYear: String,
  },
  identificationInfoForm: {
    systemCode: String,
    systemType: String,
    commercialRegistryNumber: String,
    nationalId: String,
    taxRegime: String,
    symbole: String,
    branchNumber: String,
    legalEntitysimple: String,
    residenceCardOrPassport: String,
    issueDate: String,
    legalFormCode: String,
    socialSecurityNumber: String,
    legalForm: String,
  },
  legalRepresentativeForm: {
    repName: String,
    repNationality: String,
    repID: String,
    repPhone: String,
    repIssueDate: String,
    repTitle: String,
    repAppointmentDate: String,
    ownerName: String,
    ownerTitle: String,
    ownerNationality: String,
    ownerIdNumber: String,
    ownerIdIssueDate: String,
    ownerPhone: String,
  },
}, {
  timestamps: true // Optional: adds createdAt and updatedAt
});

module.exports = mongoose.model('FormData', formDataSchema);
